//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySuKien
{
    public partial class CaptchaList
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;
        protected global::System.Web.UI.WebControls.Label lblSuccess;
        protected global::System.Web.UI.WebControls.TextBox txtMa;
        protected global::System.Web.UI.WebControls.Button btnAdd;
        protected global::System.Web.UI.WebControls.Label lblCount;
        protected global::System.Web.UI.WebControls.Button btnClearAll;
        protected global::System.Web.UI.WebControls.Repeater rptList;
        protected global::System.Web.UI.WebControls.PlaceHolder phEmpty;
    }
}